services:
  - type: web
    name: smart-assistant-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000